version: '3.7'
services:
  app_1:
    build: .
    ports:
      # - "3000:3000"
      # - "8080:8080"
      - 10000-10003:8081
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    # network_mode: host
  app_2:
    build: .
    ports:
      # - "3000:3000"
      # - "8080:8080"
      - 10000-10003:8081
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  app_3:
    build: .
    ports:
      # - "3000:3000"
      # - "8080:8080"
      - 10000-10003:8081
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  app_4:
    build: .
    ports:
      # - "3000:3000"
      # - "8080:8080"
      - 10000-10003:8081
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
  nginx:
    image: nginx:alpine3.18-slim
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    depends_on:
    - app_1
    - app_2
    - app_3
    - app_4
    # network_mode: host

